AWSTemplateFormatVersion: 2010-09-09
Description: > 
  s3 IAM role to list bucket

Resources:
  S3FullAccessRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - 'ec2.amazonaws.com'
      Path: /
      Policies:
        - PolicyName: S3FullAccessTest
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 's3:ListBucket'
                Resource: 'ENTER_BucketARN'
  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref S3FullAccessRole
      Path: /
            
